---
# clickhouse variables
clickhouse_version: "22.7.7.24"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static

# vector variables
vector_version: "0.47.0"  
vector_url: "https://packages.timber.io/vector/0.47.0/vector-0.47.0-aarch64-unknown-linux-musl.tar.gz"
vector_install_dir: "/opt/vector"
vector_config_path: "/etc/vector/vector.toml"