---
  - src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 

  - src: https://github.com/alex-bel31/ansible-lighthouse.git
    scm: git
    version: "1.0.0"
    name: lighthouse 

  - src: https://github.com/alex-bel31/ansible-vector.git
    scm: git
    version: "1.0.0"
    name: vector 